# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Importing_Data.py
# Created on: 2022-01-08 15:32:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Subadult_Bluestriped_Grunt_Binary_HSM_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Binary_HSM.tif"
Subadult_Bluestriped_Grunt_Binary_HSM__2_ = Subadult_Bluestriped_Grunt_Binary_HSM_tif
Subadult_Bluestriped_Grunt_Binary_HSM_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Binary_HSM_10m.tif"
Subadult_Bluestriped_Grunt_Binary_HSM_10m__2_ = Subadult_Bluestriped_Grunt_Binary_HSM_10m_tif
Subadult_Bluestriped_Grunt_HSM_10m__2_ = Subadult_Bluestriped_Grunt_Binary_HSM_10m_tif
Subadult_Bluestriped_Grunt_Cost_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Cost.tif"
Subadult_Bluestriped_Grunt_Cost__2_ = Subadult_Bluestriped_Grunt_Cost_tif
Subadult_Bluestriped_Grunt_Cost_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Cost_10m.tif"
Subadult_Bluestriped_Grunt_Cost_10m__2_ = Subadult_Bluestriped_Grunt_Cost_10m_tif
Subadult_Bluestriped_Grunt_HSM_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_HSM_10m.tif"
Subadult_Gray_Snapper_Binary_HSM_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Binary_HSM.tif"
Subadult_Gray_Snapper_Binary_HSM__2_ = Subadult_Gray_Snapper_Binary_HSM_tif
Subadult_Gray_Snapper_Binary_HSM_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Binary_HSM_10m.tif"
Subadult_Gray_Snapper_Binary_HSM_10m__2_ = Subadult_Gray_Snapper_Binary_HSM_10m_tif
Subadult_Gray_Snapper_Cost_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Cost.tif"
Subadult_Gray_Snapper_Cost__2_ = Subadult_Gray_Snapper_Cost_tif
Subadult_Gray_Snapper_Cost_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Cost_10m.tif"
Subadult_Gray_Snapper_Cost_10m__2_ = Subadult_Gray_Snapper_Cost_10m_tif
Subadult_Gray_Snapper_HSM_10m_tif = "Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_HSM_10m.tif"
Subadult_Gray_Snapper_HSM_10m__2_ = Subadult_Gray_Snapper_HSM_10m_tif
Stuart_MSc_Ch2_gdb = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb"
Stuart_MSc_Ch2_gdb__2_ = Stuart_MSc_Ch2_gdb
Subadult_Bluestriped_Grunt_Binary_HSM = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Binary_HSM"
Subadult_Bluestriped_Grunt_Binary_HSM_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Binary_HSM_10m"
Subadult_Bluestriped_Grunt_Cost = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Cost"
Subadult_Bluestriped_Grunt_Cost_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Cost_10m"
Subadult_Gray_Snapper_Binary_HSM = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Binary_HSM"
Subadult_Gray_Snapper_Binary_HSM_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Binary_HSM_10m"
Subadult_Gray_Snapper_Cost = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Cost"
Subadult_Gray_Snapper_Cost_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Cost_10m"
HAE_SCIU_avg_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\HSMs\\MaxEnt\\Subadult_Bluestriped_Grunt\\HAE_SCIU_avg.asc"
Subadult_Bluestriped_Grunt_HSM = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_HSM"
Subadult_Bluestriped_Grunt_HSM__2_ = Subadult_Bluestriped_Grunt_HSM
LUT_GRIS_avg_asc = "Z:\\Courtney\\Stuart_MSc_Ch1\\HSMs\\MaxEnt\\Subadult_Gray_Snapper\\LUT_GRIS_avg.asc"
Subadult_Gray_Snapper_HSM = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_HSM"
Subadult_Gray_Snapper_HSM__2_ = Subadult_Gray_Snapper_HSM
patches_shp = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp"
Subadult_Gray_Snapper_Nodes = patches_shp
Subadult_Gray_Snapper_Nodes__2_ = Subadult_Gray_Snapper_Nodes
Subadult_Gray_Snapper_HSM_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_HSM_10m"
Subadult_Gray_Snapper_Mean_Node_Suitability = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability"
Subadult_Gray_Snapper_Mean_Node_Suitability__2_ = Subadult_Gray_Snapper_Mean_Node_Suitability
Subadult_Gray_Snapper_Mean_Node_Suitability__3_ = Subadult_Gray_Snapper_Mean_Node_Suitability__2_
Subadult_Gray_Snapper_Quality_Weighted_Area_csv = Subadult_Gray_Snapper_Mean_Node_Suitability__3_
Subadult_Gray_Snapper_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m"
patches_shp__2_ = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp"
Subadult_Bluestriped_Grunt_Nodes = patches_shp__2_
Subadult_Bluestriped_Grunt_Nodes__2_ = Subadult_Bluestriped_Grunt_Nodes
Subadult_Bluestriped_Grunt_HSM_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_HSM_10m"
Subadult_Bluestriped_Grunt_Mean_Node_Suitability = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability"
Subadult_Bluestriped_Grunt_Mean_Node_Suitability__2_ = Subadult_Bluestriped_Grunt_Mean_Node_Suitability
Subadult_Bluestriped_Grunt_Mean_Node_Suitability__3_ = Subadult_Bluestriped_Grunt_Mean_Node_Suitability__2_
Subadult_Bluestriped_Grunt_Quality_Weighted_Area_csv = Subadult_Bluestriped_Grunt_Mean_Node_Suitability__3_
Subadult_Bluestriped_Grunt_10m = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m"
Least_Cost_Planar_links_shp = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp"
Subadult_Bluestriped_Grunt_LCP = Least_Cost_Planar_links_shp
Subadult_Bluestriped_Grunt_LCP__2_ = Subadult_Bluestriped_Grunt_LCP
Least_Cost_Planar_links_shp__2_ = "Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp"
Subadult_Gray_Snapper_LCP = Least_Cost_Planar_links_shp__2_
Subadult_Gray_Snapper_LCP__2_ = Subadult_Gray_Snapper_LCP

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2_Scratch.gdb"
arcpy.env.workspace = "Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb"

# Process: Raster To Geodatabase (multiple)
arcpy.RasterToGeodatabase_conversion("Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Binary_HSM.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Binary_HSM_10m.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Cost.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_Cost_10m.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Bluestriped_Grunt_HSM_10m.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Binary_HSM.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Binary_HSM_10m.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Cost.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_Cost_10m.tif;Z:\\Courtney\\Stuart_MSc_Ch2\\GIS_Files\\Subadult_Gray_Snapper_HSM_10m.tif", Stuart_MSc_Ch2_gdb, "")

# Process: Define Projection
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_Binary_HSM, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (2)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_Binary_HSM_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (3)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_Cost, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (5)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_Cost_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (6)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_Binary_HSM, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (7)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_Binary_HSM_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (8)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_Cost, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (9)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_Cost_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: ASCII to Raster (2)
arcpy.ASCIIToRaster_conversion(HAE_SCIU_avg_asc, Subadult_Bluestriped_Grunt_HSM, "FLOAT")

# Process: Define Projection (12)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_HSM, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: ASCII to Raster
arcpy.ASCIIToRaster_conversion(LUT_GRIS_avg_asc, Subadult_Gray_Snapper_HSM, "FLOAT")

# Process: Define Projection (11)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_HSM, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(patches_shp, Stuart_MSc_Ch2_gdb, "Subadult_Gray_Snapper_Nodes", "", "Id \"Id\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp,Id,-1,-1;Id0 \"Id0\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp,Id0,-1,-1;Area \"Area\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp,Area,-1,-1;Perim \"Perim\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp,Perim,-1,-1;Capacity \"Capacity\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\patches.shp,Capacity,-1,-1", "")

# Process: Define Projection (13)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_Nodes, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (10)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_HSM_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(Subadult_Gray_Snapper_Nodes__2_, "Id", Subadult_Gray_Snapper_HSM_10m__2_, Subadult_Gray_Snapper_Mean_Node_Suitability, "DATA", "MEAN_STD")

# Process: Add Field
arcpy.AddField_management(Subadult_Gray_Snapper_Mean_Node_Suitability, "QUALITY_WEIGHTED_AREA", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Subadult_Gray_Snapper_Mean_Node_Suitability__2_, "QUALITY_WEIGHTED_AREA", "[AREA] * [MEAN]", "VB", "")

# Process: Table to Table
arcpy.TableToTable_conversion(Subadult_Gray_Snapper_Mean_Node_Suitability__3_, Subadult_Gray_Snapper_10m, "Subadult_Gray_Snapper_Quality_Weighted_Area.csv", "", "Id \"Id\" true true false 4 Long 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,Id,-1,-1;COUNT \"COUNT\" true true false 4 Long 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,COUNT,-1,-1;AREA \"AREA\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,AREA,-1,-1;MEAN \"MEAN\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,MEAN,-1,-1;STD \"STD\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,STD,-1,-1;QUALITY_WEIGHTED_AREA \"QUALITY_WEIGHTED_AREA\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Gray_Snapper_Mean_Node_Suitability,QUALITY_WEIGHTED_AREA,-1,-1", "")

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(patches_shp__2_, Stuart_MSc_Ch2_gdb, "Subadult_Bluestriped_Grunt_Nodes", "", "Id \"Id\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp,Id,-1,-1;Id0 \"Id0\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp,Id0,-1,-1;Area \"Area\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp,Area,-1,-1;Perim \"Perim\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp,Perim,-1,-1;Capacity \"Capacity\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\patches.shp,Capacity,-1,-1", "")

# Process: Define Projection (14)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_Nodes, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Define Projection (4)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_HSM_10m, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Zonal Statistics as Table (2)
arcpy.gp.ZonalStatisticsAsTable_sa(Subadult_Bluestriped_Grunt_Nodes__2_, "Id", Subadult_Bluestriped_Grunt_HSM_10m__2_, Subadult_Bluestriped_Grunt_Mean_Node_Suitability, "DATA", "MEAN_STD")

# Process: Add Field (2)
arcpy.AddField_management(Subadult_Bluestriped_Grunt_Mean_Node_Suitability, "QUALITY_WEIGHTED_AREA", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(Subadult_Bluestriped_Grunt_Mean_Node_Suitability__2_, "QUALITY_WEIGHTED_AREA", "[AREA] * [MEAN]", "VB", "")

# Process: Table to Table (2)
arcpy.TableToTable_conversion(Subadult_Bluestriped_Grunt_Mean_Node_Suitability__3_, Subadult_Bluestriped_Grunt_10m, "Subadult_Bluestriped_Grunt_Quality_Weighted_Area.csv", "", "Id \"Id\" true true false 4 Long 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,Id,-1,-1;COUNT \"COUNT\" true true false 4 Long 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,COUNT,-1,-1;AREA \"AREA\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,AREA,-1,-1;MEAN \"MEAN\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,MEAN,-1,-1;STD \"STD\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,STD,-1,-1;QUALITY_WEIGHTED_AREA \"QUALITY_WEIGHTED_AREA\" true true false 8 Double 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Geodatabases\\Stuart_MSc_Ch2.gdb\\Subadult_Bluestriped_Grunt_Mean_Node_Suitability,QUALITY_WEIGHTED_AREA,-1,-1", "")

# Process: Feature Class to Feature Class (3)
arcpy.FeatureClassToFeatureClass_conversion(Least_Cost_Planar_links_shp, Stuart_MSc_Ch2_gdb, "Subadult_Bluestriped_Grunt_LCP", "", "Id \"Id\" true true false 254 Text 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp,Id,-1,-1;ID1 \"ID1\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp,ID1,-1,-1;ID2 \"ID2\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp,ID2,-1,-1;Dist \"Dist\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp,Dist,-1,-1;DistM \"DistM\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Bluestriped_Grunt_10m\\Least_Cost_Planar-links.shp,DistM,-1,-1", "")

# Process: Define Projection (15)
arcpy.DefineProjection_management(Subadult_Bluestriped_Grunt_LCP, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

# Process: Feature Class to Feature Class (4)
arcpy.FeatureClassToFeatureClass_conversion(Least_Cost_Planar_links_shp__2_, Stuart_MSc_Ch2_gdb, "Subadult_Gray_Snapper_LCP", "", "Id \"Id\" true true false 254 Text 0 0 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp,Id,-1,-1;ID1 \"ID1\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp,ID1,-1,-1;ID2 \"ID2\" true true false 9 Long 0 9 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp,ID2,-1,-1;Dist \"Dist\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp,Dist,-1,-1;DistM \"DistM\" true true false 33 Double 15 32 ,First,#,Z:\\Courtney\\Stuart_MSc_Ch2\\Graphab\\Subadult_Gray_Snapper_10m\\Least_Cost_Planar-links.shp,DistM,-1,-1", "")

# Process: Define Projection (16)
arcpy.DefineProjection_management(Subadult_Gray_Snapper_LCP, "PROJCS['NAD_1983_StatePlane_Florida_East_FIPS_0901',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',200000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-81.0],PARAMETER['Scale_Factor',0.9999411764705882],PARAMETER['Latitude_Of_Origin',24.33333333333333],UNIT['Meter',1.0]]")

